FROM python:3.9-alpine3.13
LABEL maintainer="adityaonx"

ENV PYTHONUNBUFFERED 1

COPY ./requirements.txt /tmp/requirements.txt
COPY ./app /app
COPY ./requirements.txt /tmp/requirements.txt

WORKDIR /app
EXPOSE 8080

RUN python -m venv /py && \
    /py/bin/pip install --upgrade pip && \
    /py/bin/pip install -r /tmp/requirements.txt && \
    rm -rf /tmp && \
    adduser \
        --disabled-password \
        --no-create-home \
        adit-django-user

ENV PATH="/py/bin:$PATH"

USER adit-django-user